#!/usr/bin/env bash
# Bash script with commands to automate your fix.

sudo rm /etc/nginx/sites-enabled/default

sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/

sudo service nginx restart
